### ISSUE TITLE
add support for universal sentence encoder cmlm

### ISSUE THREAD

**Issue by bhavsarpratik** [jina-ai/jina-hub#1497]
Add support for [universal-sentence-encoder-cmlm](https://tfhub.dev/google/universal-sentence-encoder-cmlm/en-base/1) in `UniversalSentenceEncoder` and change default to this model. This model seems smaller and better.

**Comment by carlosb1** [comment]
Is the idea to replace the current encoder or do you want to include  another new one? I see that they are preprocessing the input data to a bert format, I don't have clear if it must be included also in this new "encoder".

**Comment by JoanFM** [comment]
> Is the idea to replace the current encoder or do you want to include another new one? I see that they are preprocessing the input data to a bert format, I don't have clear if it must be included also in this new "encoder".

This should be about guaranteeing that this model is supported and changing the default model without breaking the support for the current models.

We may need to add the logic to decide which models require some preprocessing or not.

**Comment by JoanFM** [comment]
maybe we can add an optional parameter with the preprocessor model that is applied if the parameter is not Nond

**Comment by carlosb1** [comment]
@JoanFM  do you have coverage to verify that it doesn't break anything?

**Comment by JoanFM** [comment]
> @JoanFM do you have coverage to verify that it doesn't break anything?

we can guarantee current unittest works with current model

**Comment by carlosb1** [comment]
I ran the docker for the `UniversalSentenceEncoder` I got this:

```
================== 4 passed, 55 warnings in 60.14s (0:01:00) ===================
Exception ignored in: <function CapturableResourceDeleter.__del__ at 0x7fc42dda4d40>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/tracking/tracking.py", line 207, in __del__
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 2031, in eager_mode
TypeError: 'NoneType' object is not callable
Removing intermediate container 7b4d713516bf
 ---> ead93e5fc23f
Step 6/6 : ENTRYPOINT ["jina", "pod", "--uses", "config.yml"]
 ---> Running in bdeda0749473
Removing intermediate container bdeda0749473
 ---> fec2f755ca91
Successfully built fec2f755ca91
Successfully tagged sentence_encoder:latest

```

Anyway, I think, it is passing  the tests.

**Comment by carlosb1** [comment]
I did a first [implementation](https://github.com/carlosb1/jina-hub/tree/1497_cmlm_encoder/encoders). I got some conclusions: 
- This encoder only is supported for tensorflow 2.4.0... It could be more urgent to freeze the tensorflow version, because this implementation wil not work for older releases (previous 2.4.0)..
-  The implementation forced me to include an initialization and encoder functions... This smell code can be a symptom that it has more sense to move all this logic to another encoder (single responsibility principle)
- If the tensorflow library is frozen, it can be necessary to verify which cuda is being [used](https://github.com/tensorflow/tensorflow/issues/42076), I got errors from my cuda 11.0 (not only developing this encoder)

I added some tests, I only would need verify the size of the embedding vector. Finally, sorry for all my "complaints", I only want to provide feedback if it is useful for you.

**Comment by JoanFM** [comment]
> I did a first [implementation](https://github.com/carlosb1/jina-hub/tree/1497_cmlm_encoder/encoders). I got some conclusions:
> 
> * This encoder only is supported for tensorflow 2.4.0... It could be more urgent to freeze the tensorflow version, because this implementation wil not work for older releases (previous 2.4.0)..
> * The implementation forced me to include an initialization and encoder functions... This smell code can be a symptom that it has more sense to move all this logic to another encoder (single responsibility principle)
> * If the tensorflow library is frozen, it can be necessary to verify which cuda is being [used](https://github.com/tensorflow/tensorflow/issues/42076), I got errors from my cuda 11.0 (not only developing this encoder)
> 
> I added some tests, I only would need verify the size of the embedding vector. Finally, sorry for all my "complaints", I only want to provide feedback if it is useful for you.

may u open a Draft PR so that we can discuss while looking at the changes?

**Comment by carlosb1** [comment]
II didn't link the PR. This issue should be closed
